version: "3"
services:
  seata-server:
    image: seataio/seata-server:1.5.0
    # hostname: seata-server
    container_name: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    volumes:
      - ./conf/application.yml:/seata-server/resources/application.yml
    environment:
      - SEATA_PORT=8091
      - SEATA_IP=192.168.1.53
    restart: always
networks:
  default:
    external:
      name: smartcity